{
  "hash": "13bb1c6e8f0ad246039b2708376bb9f4",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"WDI Exploratory Analysis\"\nauthor: \"Liane Muir\"\ndate: \"2025-02-25\"\nformat:\n  revealjs:\n    slide-level: 2\n    theme: moon\n    transition: slide\n    scrollable: true\n    code-line-numbers: true\n    embed-resources: true\n    footer: \"Footer text\"\neditor:\n  render-on-save: true\noutput-dir: docs \n---\n\n\n## Selection of Indicators\n\nI chose three indicators to analyze from the World Development Indicators (WDI) dataset:\n\n:::{.incremental}\n- Inflation Rate\n- Life Expectancy\n- GDP per Capita\n:::\n\n:::{.fragment .fade-in}\nThese indicators are respectively considered measures of economic stability, health, and economic prosperity.  \n:::\n\n## Summary Statistics\n\nThe distribution of our key economic and health indicators across 217 countries in 2022:\n\n::: {#10d4d7fb .cell execution_count=1}\n\n::: {.cell-output .cell-output-display}\n![Distribution of key economic and health indicators. This figure shows the distribution of three indicators across countries in 2022. The density curves help elucidate overall trends. Note skews in the distributions.](05_Presentation_files/figure-revealjs/cell-2-output-1.png){width=1718 height=469}\n:::\n:::\n\n\n## Summary Statistics Cont.\n\n:::{.fragment .fade-in}\nSummary statistics for our indicator variables:\n\n|                         |       Mean |   Standard Deviation |       Min |   25th Percentile |     Median |   75th Percentile |        Max |\n|:------------------------|-----------:|---------------------:|----------:|------------------:|-----------:|------------------:|-----------:|\n| Inflation Rate (%)      |    12.4939 |             19.6824  |  -6.68732 |           5.51813 |    7.96757 |           11.6656 |    171.205 |\n| Life Expectancy (Years) |    72.4165 |              7.71332 |  52.997   |          66.782   |   73.5146  |           78.475  |     85.377 |\n| GDP per Capita (USD)    | 20345.7    |          31308.9     | 259.025   |        2570.56    | 7587.59    |        25982.6    | 240862     |\n\n\n:::\n\n:::{.fragment .fade-in-then-out}\nThe histogram for Inflation Rate had a right-skewed distribution, showing that most countries have inflation rates below 15%. The range of values goes from -6.69% (deflation) to 171.2% (hyperinflation).\n\nLet's take a closer look at the number of countries in each inflation category.\n:::\n\n## Exploratory Analysis \n\nAs we see in the figure below, the highest number of countries are in the \"Elevated Inflation\" category:\n\n::: {#cell-fig-barplot .cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![Bar plot showing the number of countries by inflation category. This figure provides a detailed count of the number of countries within each inflation rate category.](05_Presentation_files/figure-revealjs/fig-barplot-output-1.png){#fig-barplot width=949 height=565}\n:::\n:::\n\n\n## Exploratory Analysis Cont. \n\nSo what are the relationships between these indicators? \nIs there a relationship between GDP per Capita (economic prosperity) and life expectancy (overall population health)? Let's see.\n\n:::{.fragment .fade-in}\n\n::: {#cell-fig-scatter .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Scatter plot of GDP per Capita vs Life Expectancy. This figure shows the relationship between GDP per Capita and Life Expectancy across countries, categorized by inflation rates. A log scale is used for GDP per Capita to better visualize the wide range of values. The regression line illustrates the overall trend and relationship between GDP and life expectancy. Data source: [World Development Indicators](https://databank.worldbank.org/source/world-development-indicators).](05_Presentation_files/figure-revealjs/fig-scatter-output-1.png){#fig-scatter width=1256 height=687}\n:::\n:::\n\n\n:::\n\n## Exploratory Analysis Summary\n\n- Inflation Rates: The distribution is right-skewed, with most countries experiencing moderate to elevated inflation (2–10%). A small subset faces hyperinflation (>50%).\n- Life Expectancy: Most countries cluster around 70–80 years, with a global average of 72.4 years. Higher life expectancy is observed in wealthier nations.\n- GDP per Capita: Strongly right-skewed, indicating economic disparity. A few high-income countries significantly raise the average.\n\n**Key Insights**:\n\n- Countries with higher GDP per capita tend to have higher life expectancy (positive correlation).\n- Inflation trends vary widely, with some nations facing extreme economic instability.\n- Economic growth is strongly linked to better health outcomes, aligning with global research.\n\n# Thank You!\n\n",
    "supporting": [
      "05_Presentation_files"
    ],
    "filters": [],
    "includes": {}
  }
}