{
  "hash": "3a89d157a984709e8cb666d00083dc06",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"WDI Data Exploratory Analysis\"\nsubtitle: \"QTM 350 Problem Set 05\"\nauthor: \"Liane Muir\"\ndate: \"2025-02-25\"\nformat:\n  html:\n    theme: cosmo  # You can choose any supported theme\n  pdf: default\nbibliography: references.bib\n---\n\n\n## Exploratory Analysis\n\nThe three indicators I selected for my exploratory analysis of the World Development Indicators dataset:\n\n1.  Inflation Rate\n2.  Life Expectancy\n3.  GDP per Capita\n\n### Key Statistics\n\n|                         |       Mean |   Standard Deviation |       Min |   25th Percentile |     Median |   75th Percentile |        Max |\n|:------------------------|-----------:|---------------------:|----------:|------------------:|-----------:|------------------:|-----------:|\n| Inflation Rate (%)      |    12.4939 |             19.6824  |  -6.68732 |           5.51813 |    7.96757 |           11.6656 |    171.205 |\n| Life Expectancy (Years) |    72.4165 |              7.71332 |  52.997   |          66.782   |   73.5146  |           78.475  |     85.377 |\n| GDP per Capita (USD)    | 20345.7    |          31308.9     | 259.025   |        2570.56    | 7587.59    |        25982.6    | 240862     |\n\n\n::: {#cell-fig-histograms .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![Distribution of key economic and health indicators. This figure shows the distribution of three indicators across countries in 2022.The density curves help elucidate overall trends.](Assignment05_files/figure-html/fig-histograms-output-1.png){#fig-histograms width=1718 height=469}\n:::\n:::\n\n\n### Analysis Summary\n\n#### Inflation Rate\n\nAcross the 217 countries documented in this dataset, inflation rates vary (*mean* = 12.49%; *SD* = 19.68%), but a right-skewed distribution (@fig-histograms) shows that most countries have inflation rates below 15%. The range of values goes from -6.69% (deflation) to 171.2% (hyperinflation).\n\nSome more probing gives a more detailed count of the number of countries within each inflation rate category:\n\n| Inflation Category         |   Number of Countries |\n|:---------------------------|----------------------:|\n| Low Inflation (<2%)        |                     6 |\n| Moderate Inflation (2-5%)  |                    29 |\n| Elevated Inflation (5-10%) |                    76 |\n| High Inflation (10-50%)    |                    53 |\n| Hyperinflation (>50%)      |                     5 |\n| Missing Data               |                    48 |\n\n\nAs in the table above, we see in @fig-barplot that the \"Elevated Inflation\" category has the highest number of countries.\n\n::: {#cell-fig-barplot .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Bar plot showing the number of countries by inflation category. This figure provides a detailed count of the number of countries within each inflation rate category.](Assignment05_files/figure-html/fig-barplot-output-1.png){#fig-barplot width=949 height=565}\n:::\n:::\n\n\n#### Life Expectancy\n\nTher average life expectancy in our dataset is 72.4 years (*SD* = 7.7 years), and the range runs from 53 years to 85.4 years. A slightly-left skewed distribution (@fig-histograms) that more measured countries maintain higher life expectancy values, clustering around 70-80 years.\n\n#### GDP per Capita\n\nThe distribution (@fig-histograms) of GDP per Capita, typically a measure of economic prosperity, is notably right-skewed, indicating that most countries in the dataset have lower GDP, while a few wealthier countries raise the mean (\\$20,345). The standard deviation for these values is high at \\$31,309.\n\n::: {#cell-fig-scatter .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![Scatter plot of GDP per Capita vs Life Expectancy. This figure shows the relationship between GDP per Capita and Life Expectancy across countries, categorized by inflation rates. A log scale is used for GDP per Capita to better visualize the wide range of values. The regression line illustrates the overall trend and relationship between GDP and life expectancy. Data source: [World Development Indicators](https://databank.worldbank.org/source/world-development-indicators).](Assignment05_files/figure-html/fig-scatter-output-1.png){#fig-scatter width=1256 height=687}\n:::\n:::\n\n\nAnalysis of the relationship between life expectancy and GDP per capita reveals a positive correlation between the two variables (@fig-scatter).\n\nSimilar relationships have been observed in various studies, clarifying the relationship between economic development and health outcomes. One study found that with increases in GDP per capita, life expectancy at birth increased and infant mortality rates lowered (a stronger relationship occuring in countries with lower levels of income inequality) [@miladinov2020socioeconomic]. A 2005-2015 cross-sectional analysis focused on the relationship between GDP and life expectancy in Russia, also showed a positive relationship between the two variables [@shkolnikov2019patterns].\n\nThese articles emphasize that economic development promotes better health outocomes through improved living conditions, healthcare access, and quality of life.\n\n````\n\n",
    "supporting": [
      "Assignment05_files"
    ],
    "filters": [],
    "includes": {}
  }
}